name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to 'master' if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
